apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
spec:
  releaseName: istiod
  targetNamespace: istio-system
  chart:
    spec:
      chart: ./manifests/charts/istio-control/istio-discovery
      sourceRef:
        kind: GitRepository
        name: istio
        namespace: flux-system
  interval: 1m0s
  install:
    remediation:
      retries: 3  