apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
spec:
  releaseName: istio-ingress
  targetNamespace: istio-system
  chart:
    spec:
      chart: ./manifests/charts/gateways/istio-ingress
      sourceRef:
        kind: GitRepository
        name: istio
        namespace: flux-system
  interval: 1m0s
  install:
    remediation:
      retries: 3         