apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
spec:
  releaseName: istio-base
  chart:
    spec:
      chart: ./manifests/charts/base
      sourceRef:
        kind: GitRepository
        name: istio
        namespace: flux-system
  interval: 1m0s
  install:
    remediation:
      retries: 3
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
spec:
  releaseName: istiod
  chart:
    spec:
      chart: ./manifests/charts/istio-control/istio-discovery
      sourceRef:
        kind: GitRepository
        name: istio
        namespace: flux-system
  interval: 1m0s
  install:
    remediation:
      retries: 3   
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
spec:
  releaseName: istio-ingress
  chart:
    spec:
      chart: ./manifests/charts/gateways/istio-ingress
      sourceRef:
        kind: GitRepository
        name: istio
        namespace: flux-system
  interval: 1m0s
  install:
    remediation:
      retries: 3         